### ISSUE TITLE
What is this libs current status?

### ISSUE THREAD

**Issue by iwaisman** [ktonga/akka-contextual-actor#1]
The last update is from over a year ago. That and the fact that this is not published on any ivy/maven repo and it has not been updated to scala 2.11 suggests this is abandoned. Is this true?

**Comment by ktonga** [comment]
Hi @iwaisman sorry for the veeeery late reply :) for some reason (github bug) I stopped following all projects of my own.

Originally I created this project to cover my specific needs at job I also contributed to akka the ability to add custom values to MDC, then I stopped using akka for a while and I forgot about this project, but if I see interest from the people I would consider deploy/maintain/accept PRs/etc.
